adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jyoti.behera85@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: jyobeer123
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
